name: CD - Deploy

on:
  push:
    branches: [ main ]
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/sentiment-api 
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha
            
      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infrastructure/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-huggingface:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Hugging Face CLI
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
          
      - name: Login to Hugging Face
        run: |
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}
          
      - name: Deploy to Hugging Face Spaces
        run: |
          python scripts/deploy_to_huggingface.py
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: sentiment-analysis-api
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}/sentiment-api:sha-${{ github.sha }}