name : CI - Test and Build

on:
  push:
    branches : [main]
  pull_request:
    branches : [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black isort mypy

      - name: Check code formatting
        run: |
          black --check .
          isort --check-only --profile black .
          
      - name: Type checking
        run: |
          mypy app/ --ignore-missing-imports
          
      - name: Run unit tests
        run: |
          pytest tests/unit/ --cov=app
          
      - name: Run integration tests
        run: |
          pytest tests/integration/ -v

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build API Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: infrastructure/docker/Dockerfile
          push: false
          tags: sentiment-api:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test Docker container
        run: |
          docker run --name test-api -d -p 8080:8080 sentiment-api:test
          sleep 10  # Wait for container to start
          curl -f http://localhost:8080/health || exit 1
          docker logs test-api
          docker stop test-api